name: Build
on: [pull_request, workflow_call, workflow_dispatch]

jobs:
  build-android:
    name: ğŸ¤– Build Android
    uses: ./.github/workflows/build-android.yml

  build-ios:
    name: ğŸ Build iOS
    uses: ./.github/workflows/build-ios.yml

  build-linux:
    name: ğŸ§ Build Linux
    uses: ./.github/workflows/build-linux.yml

  build-macos:
    name: ğŸ Build macOS
    uses: ./.github/workflows/build-macos.yml

  build-windows:
    name: ğŸ Build Windows
    uses: ./.github/workflows/build-windows.yml

  build-web:
    name: ğŸŒ Build Web
    uses: ./.github/workflows/build-web.yml
